copy \work\cnntest\Console-WIntest\DIalogStruct.h /y
copy \work\cnntest\Console-WIntest\CString.h /y
copy \work\cnntest\Console-WIntest\Calculator.h /y
copy \work\cnntest\Console-WIntest\ControlGroup.h /y
copy \work\cnntest\Console-WIntest\CDialog.h /y
copy \work\cnntest\Console-WIntest\CSageTools.h /y
copy \work\cnntest\Console-WIntest\Point3D.h /y
copy \work\cnntest\Console-WIntest\CQuickControls.h /y
copy \work\cnntest\Console-WIntest\CVisualSort.h /y
copy \work\cnntest\Console-WIntest\CColorWheelWidget.h /y
copy \work\cnntest\Console-WIntest\CPoint.h /y
copy \work\cnntest\Console-WIntest\CQuickMenu.h /y
copy \work\cnntest\Console-WIntest\CTextWidget.h /y
copy \work\cnntest\Console-WIntest\CHandleSliderMsg.h /y
copy \work\cnntest\Console-WIntest\CSlider.h /y
copy \work\cnntest\Console-WIntest\CMemClass.h /y
copy \work\cnntest\Console-WIntest\Cmenu.h /y
copy \work\cnntest\Console-WIntest\CPgr.h /y
copy \work\cnntest\Console-WIntest\CWindowHandler.h /y
copy \work\cnntest\Console-WIntest\CSageTypes.h /y
copy \work\cnntest\Console-WIntest\CEditBox.h /y
copy \work\cnntest\Console-WIntest\CArrowBox.h /y
copy \work\cnntest\Console-WIntest\CButton.h /y
copy \work\cnntest\Console-WIntest\SageOpt.h /y
copy \work\cnntest\Console-WIntest\CDavinci.h /y
copy \work\cnntest\Console-WIntest\CSageBox.h /y
copy \work\cnntest\Console-WIntest\Cpaswindow.h /y
copy \work\cnntest\Console-WIntest\CWindow.h /y
copy \work\cnntest\Console-WIntest\CRawBitmap.h /y
copy \work\cnntest\Console-WIntest\Sage.h /y
copy \work\cnntest\Console-WIntest\CLedDisplayWidget.h /y
copy \work\cnntest\Console-WIntest\CDialWidget.h /y
copy \work\cnntest\Console-WIntest\CColorSelector.h /y
