
copy \work\cnntest\Console-WIntest\CBitmapWidget.h             /y
copy \work\cnntest\Console-WIntest\CButton.h                   /y
copy \work\cnntest\Console-WIntest\CButtonBuilder.h            /y
copy \work\cnntest\Console-WIntest\CButtonHandler.h            /y
copy \work\cnntest\Console-WIntest\CControlStyles.h            /y
copy \work\cnntest\Console-WIntest\CDavinci.h                  /y
copy \work\cnntest\Console-WIntest\CDevString.h                /y
copy \work\cnntest\Console-WIntest\CDialog.h                   /y
copy \work\cnntest\Console-WIntest\CDialogParser.h             /y
copy \work\cnntest\Console-WIntest\CEditBox.h                  /y
copy \work\cnntest\Console-WIntest\CEditBoxHandler.h           /y
copy \work\cnntest\Console-WIntest\CJpeg.h                     /y
copy \work\cnntest\Console-WIntest\CListBox.h                  /y
copy \work\cnntest\Console-WIntest\CListBoxHandler.h           /y
copy \work\cnntest\Console-WIntest\CMemClass.h                 /y
copy \work\cnntest\Console-WIntest\Cmenu.h                     /y
copy \work\cnntest\Console-WIntest\ControlGroup.h              /y
copy \work\cnntest\Console-WIntest\COutDC.h                    /y
copy \work\cnntest\Console-WIntest\CPasWindow.h                /y
copy \work\cnntest\Console-WIntest\CPgr.h                      /y
copy \work\cnntest\Console-WIntest\CPoint.h                    /y
copy \work\cnntest\Console-WIntest\CRawBitmap.h                /y
copy \work\cnntest\Console-WIntest\CSageBox.h                  /y
copy \work\cnntest\Console-WIntest\CSageMacros.h               /y
copy \work\cnntest\Console-WIntest\CSageTypes.h                /y
copy \work\cnntest\Console-WIntest\CSlider.h                   /y
copy \work\cnntest\Console-WIntest\CSliderHandler.h            /y
copy \work\cnntest\Console-WIntest\CString.h                   /y
copy \work\cnntest\Console-WIntest\CStyleDefaults.h            /y
copy \work\cnntest\Console-WIntest\CTextWidget.h               /y
copy \work\cnntest\Console-WIntest\CWindow.h                   /y
copy \work\cnntest\Console-WIntest\CWindowHandler.h            /y
copy \work\cnntest\Console-WIntest\DIalogStruct.h              /y
copy \work\cnntest\Console-WIntest\EventOpt.h                  /y
copy \work\cnntest\Console-WIntest\Sage.h                      /y
copy \work\cnntest\Console-WIntest\SageOpt.h                   /y
copy \work\cnntest\Console-WIntest\SageString.h                /y
copy \work\cnntest\Console-WIntest\SandboxHelp.h               /y
