copy C:\work\cnntest\Console-WIntest\CPoint.h               /y
copy C:\work\cnntest\Console-WIntest\CSize.h                /y
copy C:\work\cnntest\Console-WIntest\CHandleSliderMsg.h     /y
copy C:\work\cnntest\Console-WIntest\CSageTimer.h           /y
copy C:\work\cnntest\Console-WIntest\CRawBitmap.h           /y
copy C:\work\cnntest\Console-WIntest\CSageTypes.h           /y
copy C:\work\cnntest\Console-WIntest\Sage.h                 /y
copy C:\work\cnntest\Console-WIntest\SageOpt.h              /y
copy C:\work\cnntest\Console-WIntest\ControlGroup.h         /y
copy C:\work\cnntest\Console-WIntest\CStoreValues.h         /y
copy C:\work\cnntest\Console-WIntest\Cpaswindow.h           /y
copy C:\work\cnntest\Console-WIntest\CProcessWindow.h       /y
copy C:\work\cnntest\Console-WIntest\CWindow.h              /y
copy C:\work\cnntest\Console-WIntest\CMemClass.h            /y
copy C:\work\cnntest\Console-WIntest\CQuickControls.h       /y
copy C:\work\cnntest\Console-WIntest\Point3D.h              /y
copy C:\work\cnntest\Console-WIntest\CView3D.h              /y
copy C:\work\cnntest\Console-WIntest\CString.h              /y
copy C:\work\cnntest\Console-WIntest\CSageBox.h             /y
copy C:\work\cnntest\Console-WIntest\CLockProcess.h         /y